### ISSUE TITLE
Node.js server High CPU Usage

### ISSUE THREAD

**Issue by Loyth** [wouterverweirder/kinect2#33]
Hello everybody, when I go to the Task Manager,  my Kinect Node.js server use 26% of CPU.

Do you have a solution to decrease that ?
Thanks.

**Comment by wouterverweirder** [comment]
Do you see a significant difference with launching some of the standard kinect SDK samples? Kinect 2 does demand a lot from your system.

**Comment by Loyth** [comment]
Yes, there is a significant difference. When I launch Controls Basics SDK Sample, the KinectService.exe use 10% of CPU and the app ControlsBasicsWPF.exe use 15%.

When I launch my App on the browser, the KinectService.exe use already 10% of CPU but the Node.js Server use 60% of CPU (because I stream BodyReader and DepthReader).

**Comment by wouterverweirder** [comment]
What extra processing do you do inside of your nodejs app? Sending image streams (such as depth, rgb) will demand extra CPU resources as node needs to compress / serialize that data. If you want to handle image streams and want high performance, I suggest using it in an electron app instead of serializing it over a socket to the browser.

**Comment by Loyth** [comment]
I only launch bodyReader and depthReader in my nodejs app.

I try to build electron app but I have some errors with

`npm install electron-kinect2`
